from __future__ import annotations

from enum import Enum


class LockFixState(str, Enum):
    BACKUP_RUNNING = "BACKUP_RUNNING"
    BACKUP_COMPLETED = "BACKUP_COMPLETED"
    FLUSHING = "FLUSHING"
    IO_CHECKING = "IO_CHECKING"
    UNMOUNTING = "UNMOUNTING"
    POWERING_OFF = "POWERING_OFF"
    ISOLATED = "ISOLATED"
    RECONNECT_REQUESTED = "RECONNECT_REQUESTED"
    POWERING_ON = "POWERING_ON"
    WAITING_DISK = "WAITING_DISK"
    VERIFYING_UID = "VERIFYING_UID"
    MOUNTED_READONLY = "MOUNTED_READONLY"
    VERIFYING_HASH = "VERIFYING_HASH"
    ONLINE_VERIFIED_RW = "ONLINE_VERIFIED_RW"
    QUARANTINE = "QUARANTINE"
    ERROR = "ERROR"
